### PR TITLE
Google calendar

### PR DESCRIPTION
**Pull request by CelestialChai**
Removed google folder, and context folder for  Google, added google component, added googleCalender to utils folder. Moved .env to root folder. Users should be able to sign into the event calendar. This google api doesn't use any backend, its all front end. Had to npm i gapi-script for an easier time to use the google api. 

Also edited the app.tsx to proper used the google component.

### CODE REVIEW

**Review by UnknownKonflikt — APPROVED** [review]
;)

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]
ok

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]
ok

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]

**Review by TheOnlyOneOriginalGenius — COMMENTED** [review]
ok

**Pull request merged**
