### PR TITLE
Auth backend

### PR DESCRIPTION
**Pull request by O-KenneDevWorks**
Added user auth
added events 
added auth routes
added seeds
added Insomnia import

### CODE REVIEW

**Review by UnknownKonflikt — APPROVED** [review]
Seeded

**Review by UnknownKonflikt — APPROVED** [review]
:)

**Review by UnknownKonflikt — APPROVED** [review]
Done

**Comment by UnknownKonflikt** [comment]
Done.

**Review by CelestialChai — APPROVED** [review]
Thanks for all your hard work on the back end Owen!

**Review by TheOnlyOneOriginalGenius — APPROVED** [review]

**Review by UnknownKonflikt — APPROVED** [review]
Approved

**Pull request merged**
